import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0A0A0A] px-4 py-10 text-[#FAFAFA]">
      <div className="mx-auto w-full max-w-2xl">
        <Link
          href="/"
          className="mb-8 inline-block text-sm font-semibold text-[#FF3D00] hover:underline"
        >
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-black mb-8">Terms of Service</h1>

        <div className="space-y-6 text-neutral-300">
          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing and using Ember, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Service Description</h2>
            <p className="leading-relaxed">
              Ember is an AI-powered service that generates personalized roasts based on user-provided data about their habits and lifestyle. The roasts are meant for entertainment purposes and should not be taken as professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">User Responsibilities</h2>
            <p className="leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information when using our service. You must not use our service for any illegal or harmful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Content and Roasts</h2>
            <p className="leading-relaxed">
              The roasts generated by our AI are for entertainment purposes only. We do not guarantee the accuracy or appropriateness of the content. You understand that the roasts may contain harsh or critical language as part of the service's nature.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Subscription and Payments</h2>
            <p className="leading-relaxed">
              We offer free and paid subscription tiers. Pro subscriptions will be available soon. Join our waitlist to be notified when Pro launches. Payment processing details will be available at launch.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Account Termination</h2>
            <p className="leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior. You may also request account deletion at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Disclaimer of Warranties</h2>
            <p className="leading-relaxed">
              The service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted or error-free operation. We are not liable for any damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Limitation of Liability</h2>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Changes to Terms</h2>
            <p className="leading-relaxed">
              We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#FAFAFA] mb-3">Contact</h2>
            <p className="leading-relaxed">
              For questions about these terms, please contact us through our support channels.
            </p>
          </section>
        </div>

        <p className="mt-12 text-sm text-neutral-500">
          Last updated: June 2026
        </p>
      </div>
    </main>
  );
}
